const { join } = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

(() => {
  try {
    execSync('node -c app.js', { cwd: __dirname });

    const originalUserCode = fs.readFileSync(join(__dirname, 'app.js'), 'utf-8');
    const additionalCodeToTest = 'Cgpjb25zdCBhc3NlcnQgPSByZXF1aXJlKCdhc3NlcnQnKTsKCnRyeSB7CiAgY29uc3QgYnVmZmVyU2l6ZSA9IDEwMDAwMDsKICAvLyBjaGVjayB1bnNhZmVCdWZmZXIKICBhc3NlcnQuZXF1YWwodW5zYWZlQnVmZmVyIGluc3RhbmNlb2YgQnVmZmVyLCB0cnVlLCAnYHVuc2FmZUJ1ZmZlcmAgaGFydXMgbWVydXBha2FuIGluc3RhbmNlIGRhcmkgYEJ1ZmZlcmAuIFNpbWFrIGNhcmEgbWVtYnVhdCBidWZmZXIgc2VjYXJhIHVuc2FmZSBwYWRhIG1hdGVyaTogImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzgzMyIgTWVuZ2Fsb2thc2lrYW4gQnVmZmVyLicpOwogIGFzc2VydC5lcXVhbCh1bnNhZmVCdWZmZXIubGVuZ3RoLCBidWZmZXJTaXplLCAnUGFuamFuZyBkYXJpIGB1bnNhZmVCdWZmZXJgIGhhcnVzIDEwMDAwMC4gU2ltYWsgY2FyYSBtZW5nYWxva2FzaWthbiBuaWxhaSBCdWZmZXIgcGFkYSBtYXRlcmk6ICJodHRwczovL3d3dy5kaWNvZGluZy5jb20vYWNhZGVtaWVzLzYxMC90dXRvcmlhbHMvMzM4MzMiIE1lbmdhbG9rYXNpaWthbiBCdWZmZXIuJyk7CiAgY29uc3Qgc29ydGVkVmFsdWVzID0gdW5zYWZlQnVmZmVyLnNvcnQoKGEsIGIpID0+IGIgLSBhKTsKICBhc3NlcnQubm90RXF1YWwoc29ydGVkVmFsdWVzWzBdLCAwLCAnQ2FyYSBtZW1idWF0IGJ1ZmZlciB0aWRhayBhbWFuIChgdW5zYWZlQnVmZmVyYCkgbWFzaWggc2FsYWguIFNpbWFrIGNhcmEgbWVtYnVhdCBidWZmZXIgc2VjYXJhIHVuc2FmZSBwYWRhIG1hdGVyaTogImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzgzMyIgTWVuZ2Fsb2thc2lrYW4gQnVmZmVyLicpOwoKICAvLyBjaGVjayBzYWZlQnVmZmVyCiAgYXNzZXJ0LmVxdWFsKHNhZmVCdWZmZXIgaW5zdGFuY2VvZiBCdWZmZXIsIHRydWUsICdgc2FmZUJ1ZmZlcmAgaGFydXMgbWVydXBha2FuIGluc3RhbmNlIGRhcmkgYEJ1ZmZlcmAuIFNpbWFrIGNhcmEgbWVtYnVhdCBidWZmZXIgc2VjYXJhIGBzYWZlYCBwYWRhIG1hdGVyaTogImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzgzMyIgTWVuZ2Fsb2thc2lrYW4gQnVmZmVyLicpOwogIGFzc2VydC5lcXVhbChzYWZlQnVmZmVyLmxlbmd0aCwgYnVmZmVyU2l6ZSwgJ1BhbmphbmcgZGFyaSBgc2FmZUJ1ZmZlcmAgaGFydXMgMTAwMDAwLicpOwogIGNvbnN0IHNvcnRlZFZhbHVlczIgPSBzYWZlQnVmZmVyLnNvcnQoKGEsIGIpID0+IGIgLSBhKTsKICBhc3NlcnQuZXF1YWwoc29ydGVkVmFsdWVzMlswXSwgMCwgJ0NhcmEgbWVtYnVhdCBidWZmZXIgYW1hbiAoYHNhZmVCdWZmZXJgKSBtYXNpaCBzYWxhaC4gU2ltYWsgY2FyYSBtZW5nYWxva2FzaWthbiBuaWxhaSBCdWZmZXIgcGFkYSBtYXRlcmk6ICJodHRwczovL3d3dy5kaWNvZGluZy5jb20vYWNhZGVtaWVzLzYxMC90dXRvcmlhbHMvMzM4MzMiIE1lbmdhbG9rYXNpaWthbiBCdWZmZXIuJyk7CgogIC8vIGNoZWNrIHN0cmluZ0J1ZmZlcgogIGFzc2VydC5lcXVhbChzdHJpbmdCdWZmZXIgaW5zdGFuY2VvZiBCdWZmZXIsIHRydWUsICdgc3RyaW5nQnVmZmVyYCBoYXJ1cyBtZXJ1cGFrYW4gaW5zdGFuY2UgZGFyaSBgQnVmZmVyYC4gU2ltYWsgY2FyYSBtZW1idWF0IGJ1ZmZlciBkYXJpIG5pbGFpIHN0cmluZyBwYWRhIG1hdGVyaTogImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzg0MyIgTWVuZ3ViYWggU3RyaW5nIG1lbmphZGkgQnVmZmVyIGRhbiBTZWJhbGlrbnlhLicpOwogIGFzc2VydC5lcXVhbChzdHJpbmdCdWZmZXIudG9TdHJpbmcoKSwgJ0RpY29kaW5nJywgJ0NhcmEgbWVtYnVhdCBgc3RyaW5nQnVmZmVyYCBtYXNpaCBzYWxhaC4gU2ltYWsgY2FyYSBtZW1idWF0IGJ1ZmZlciBkYXJpIG5pbGFpIHN0cmluZyBwYWRhIG1hdGVyaTogImh0dHBzOi8vd3d3LmRpY29kaW5nLmNvbS9hY2FkZW1pZXMvNjEwL3R1dG9yaWFscy8zMzg0MyIgTWVuZ3ViYWggU3RyaW5nIG1lbmphZGkgQnVmZmVyIGRhbiBTZWJhbGlrbnlhLicpOwp9IGNhdGNoIChlcnJvcikgewogIGlmIChlcnJvci5uYW1lID09PSAnQXNzZXJ0aW9uRXJyb3InKSB7CiAgICBjb25zb2xlLmVycm9yKGVycm9yLm1lc3NhZ2UpOwogICAgcHJvY2Vzcy5leGl0KDEpOwogIH0gZWxzZSB7CiAgICBjb25zb2xlLmVycm9yKGBLYW1pIGdhZ2FsIG1lbmd1amkga29kZSB5YW5nIGthbXUgdHVsaXMuIEJlcmlrdXQgZXJyb3IgeWFuZyBkaWhhc2lsa2FuOiAke2Vycm9yLm1lc3NhZ2V9XG4gU2ltYWsgZXJyb3IgdGVyc2VidXQgZGFuIHBhc3Rpa2FuIGthbXUgc3VkYWggbWVudWxpc2thbiBrb2RlIGRlbmdhbiBiZW5hciwgeWEhYCk7CiAgICBwcm9jZXNzLmV4aXQoMSk7CiAgfQp9';
    const appJSTestCode = originalUserCode + Buffer.from(additionalCodeToTest, 'base64').toString('utf-8');

    fs.writeFileSync(join(__dirname, 'app.testing.js'), appJSTestCode);

    execSync('node app.testing.js', { cwd: __dirname, stdio: 'pipe' });
    console.log('passed!');
  } catch (error) {
    const { stderr } = error;
    console.log(stderr.toString());
  } finally {
    fs.unlinkSync(join(__dirname, 'app.testing.js'));
  }
})();
